apps/blog/urls.py
from django.urls import path

from . import views

app_name='blog'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('<slug>', views.Show, name='show'),
    path('category/<int:category_id>', views.category, name='category')
]

apps/categories/urls.py
from django.urls import path
from . import views

app_name='categories'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/', views.Create.as_view(), name='create'),
    path('edit/<int:pk>', views.Edit.as_view(), name='edit'),
    path('delete/<int:pk>', views.Delete.as_view(), name='delete'),
]

apps/posts/urls.py
from django.urls import path
from django.conf.urls.static import static #For media conf
from django.conf import settings #For media conf

from . import views

app_name='posts'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/', views.Create, name='create'),
    path('edit/<int:pk>', views.Edit, name='edit'),
    path('delete/<int:pk>', views.Delete.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # For media conf

apps/users/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name="users"

urlpatterns = [
    path('register/', views.Registro.as_view(), name="register"),
    path('profile/', views.Profile, name='profile'),
]

color_y_alegria/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('nosotros/', views.nosotros, name='nosotros'),

    #includes
    path('categories/', include('apps.categories.urls')),
    path('users/', include('apps.users.urls')),
    path('posts/', include('apps.posts.urls')),
    path('blog/', include('apps.blog.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models

# Create your models here.

apps/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage
from apps.comments.forms import CommentForm
from apps.comments.models import Comments
from apps.media.models import Media
from apps.posts.models import Posts
from apps.categories.models import Categories

# Create your views here.
class Index(ListView):
    template_name = 'blog/index.html'
    model = Posts
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        posts = Posts.objects.all()
        return posts

    def get_context_data(self, *args, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['page_obj'] = context.pop('page_obj', None)
        context['categories'] = Categories.objects.all()
        return context

def Show(request, slug):
    post = get_object_or_404(Posts, slug = slug)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post = post
            form.user_id = request.user.id
            form.save()

            return redirect('blog:show', slug = slug)
    else:
        form = CommentForm()

    categories = Categories.objects.filter(id = post.category_id)
    comments = Comments.objects.filter(post_id = post.id)
    photos = Media.objects.filter(post_id = post.id)
    context = {'post': post, 'categories': categories, 'comments': comments, 'photos': photos,'form': form}

    return render(request, 'blog/show.html', context)


def category(request, category_id):
    try:
        category = get_object_or_404(Categories, id=category_id)
        posts = Posts.objects.filter(category=category_id)
        
        paginator = Paginator(posts, 5)
        page = request.GET.get('page')
        posts = paginator.get_page(page)

        return render(request, 'category/category.html',{'category':category, 'posts':posts, 'page_obj': posts, 'is_paginated': True, 'categories': Categories.objects.all})
    except:
        return render(request, 'blog/show.html')

templates/layouts/app.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Color y alegria - admin</title>

	<link rel="icon" href="{% static 'src/img/logo-icon.ico' %}">

	{% compress css %}
	<link rel="stylesheet" href="{% static 'src/output.css' %}">
	{% endcompress %}

	<style>
		aside.block{
			animation: fade 1s;
			transition: opacity 600ms, visibility 600ms;
		}
		@keyframes fade {
			0% {
				opacity: 0;
			}

			100% {
				opacity: 1;
			}
		}
	</style>
	{% block css %}{% endblock css %}

	<script>
		// On page load or when changing themes, best to add inline in `head` to avoid FOUC
		if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
			document.documentElement.classList.add('dark');
		} else {
			document.documentElement.classList.remove('dark')
		}
	</script>

</head>

<body>
	<div class="flex min-h-screen">
		<aside class="hidden min-w-[256px] w-64 bg-gray-800 sm:block menuList">
			<div class="py-5 mb-8 text-2xl tracking-widest text-center uppercase border-b-2 border-gray-800">
				<a aria-current="page" href="/" class="text-white router-link-active router-link-exact-active">Color y alegria</a>
			</div>
			<nav class="text-sm text-gray-300">
				<ul class="flex flex-col">
					<li class="px-4 py-2 text-xs font-bold tracking-wider text-gray-500 uppercase">Sitio web</li>
					<li class="px-4 cursor-pointer{% if None in request.path %}bg-gray-500 text-gray-800 {% else %} hover:bg-gray-700 {% endif %}">
						<a class="flex items-center py-3" href="{% url 'index' %}">
							<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
							</svg>
							Ir al sitio web
						</a>
					</li>
					<li class="px-4 py-3 text-xs font-bold tracking-wider text-gray-500 uppercase">Administracion</li>
					<li class="px-4 cursor-pointer{% if 'posts' in request.path %} bg-gray-500 text-gray-800 {% else %} hover:bg-gray-700 {% endif %}">
						<a href="{% url 'posts:index' %}" class="flex items-center py-3">
							<svg class="w-5 h-5 mr-2" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M5 3C3.89543 3 3 3.89543 3 5V7C3 8.10457 3.89543 9 5 9H7C8.10457 9 9 8.10457 9 7V5C9 3.89543 8.10457 3 7 3H5Z" fill="currentColor"></path>
								<path d="M5 11C3.89543 11 3 11.8954 3 13V15C3 16.1046 3.89543 17 5 17H7C8.10457 17 9 16.1046 9 15V13C9 11.8954 8.10457 11 7 11H5Z" fill="currentColor"></path>
								<path d="M11 5C11 3.89543 11.8954 3 13 3H15C16.1046 3 17 3.89543 17 5V7C17 8.10457 16.1046 9 15 9H13C11.8954 9 11 8.10457 11 7V5Z" fill="currentColor"></path>
								<path d="M11 13C11 11.8954 11.8954 11 13 11H15C16.1046 11 17 11.8954 17 13V15C17 16.1046 16.1046 17 15 17H13C11.8954 17 11 16.1046 11 15V13Z" fill="currentColor"></path>
							</svg> Publicaciones
						</a>
					</li>
					<li class="px-4 cursor-pointer{% if 'categories' in request.path %} bg-gray-500 text-gray-800 {% else %} hover:bg-gray-700 {% endif %}">
						<a href="{% url 'categories:index' %}" class="flex items-center py-3">
							<svg class="w-5 h-5 mr-2" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M5 3C3.89543 3 3 3.89543 3 5V7C3 8.10457 3.89543 9 5 9H7C8.10457 9 9 8.10457 9 7V5C9 3.89543 8.10457 3 7 3H5Z" fill="currentColor"></path>
								<path d="M5 11C3.89543 11 3 11.8954 3 13V15C3 16.1046 3.89543 17 5 17H7C8.10457 17 9 16.1046 9 15V13C9 11.8954 8.10457 11 7 11H5Z" fill="currentColor"></path>
								<path d="M11 5C11 3.89543 11.8954 3 13 3H15C16.1046 3 17 3.89543 17 5V7C17 8.10457 16.1046 9 15 9H13C11.8954 9 11 8.10457 11 7V5Z" fill="currentColor"></path>
								<path d="M11 13C11 11.8954 11.8954 11 13 11H15C16.1046 11 17 11.8954 17 13V15C17 16.1046 16.1046 17 15 17H13C11.8954 17 11 16.1046 11 15V13Z" fill="currentColor"></path>
							</svg> Categorias
						</a>
					</li>
					<li class="px-4 py-2 mt-2 text-xs font-bold tracking-wider text-gray-500 uppercase">Otros</li>
					{% if user.is_authenticated %}
					<li class="px-4 cursor-pointer hover:bg-gray-700">
						<a href="{% url 'users:profile' %}" class="flex items-center py-3">
							<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z"></path>
							</svg> 
							Perfil de usuario
						</a>
					</li>
					<li class="px-4 cursor-pointer hover:bg-gray-700">
						<a href="{% url 'logout' %}" class="flex items-center py-3">
							<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z"></path>
							</svg> 
							Cerrar sesion
						</a>
					</li>
					{% endif %}
				</ul>
			</nav>
		</aside>
		<div class="flex flex-col flex-grow bg-gray-200 dark:bg-gray-900">
			<header class="flex justify-between px-4 bg-white border-b-2 sm:justify-end sm:px-6 dark:bg-slate-800 dark:border-black">
				<button class="sm:hidden menu">
					<svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
					</svg>
				</button>
				<div class="flex gap-2">
					<div class="my-4">
						<button id="theme-toggle" type="button" class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
							<svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
								<path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path>
							</svg>
							<svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
								<path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path>
							</svg>
						</button>
					</div>
					<button id="headlessui-menu-button-47" type="button" aria-haspopup="true" aria-expanded="false" class="flex items-center px-4 py-3 my-2 ml-2 space-x-2 text-sm text-gray-600 rounded-lg dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:focus:ring-gray-700 focus:outline-none">
						
						{% if user.photo %}
						<img src="{{user.photo.url}}" alt="avatar" class="hidden object-cover w-8 h-8 mr-2 rounded-full sm:block dark:bg-gray-600 ring-2 ring-gray-400 dark:ring-gray-500">
						{% else %}
						<div class="relative w-10 h-10 mr-2 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600 ring-2 ring-gray-300 dark:ring-gray-500">
							<svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
						</div>
						{% endif %}

						{% if user.is_authenticated %}
						<span>@{{user}} ({{ user.first_name }} {{ user.last_name }})</span>
						{% endif %}
					</button>
				</div>
			</header>

			<div class="mb-auto">
				
				{% if messages %}
				<div class="p-4 sm:px-8 sm:py-4">
					<div class="p-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
						{% for message in messages %}
						<span class="font-medium">{{ message }}</span>
						{% endfor %}
					</div>
				</div>
				{% endif %}

				<div class="p-4 mt-4 sm:px-8 sm:py-4">

					<div class="bg-white border rounded-lg shadow dark:bg-gray-800 dark:border-none">
						{% block content %}{% endblock content %}
					</div>

				</div>
			</div>
		</div>
	</div>

	<script>
		var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
		var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

		// Change the icons inside the button based on previous settings
		if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
			themeToggleLightIcon.classList.remove('hidden');
		} else {
			themeToggleDarkIcon.classList.remove('hidden');
		}

		var themeToggleBtn = document.getElementById('theme-toggle');

		themeToggleBtn.addEventListener('click', function () {

			// toggle icons inside button
			themeToggleDarkIcon.classList.toggle('hidden');
			themeToggleLightIcon.classList.toggle('hidden');

			// if set via local storage previously
			if (localStorage.getItem('color-theme')) {
				if (localStorage.getItem('color-theme') === 'light') {
					document.documentElement.classList.add('dark');
					localStorage.setItem('color-theme', 'dark');
				} else {
					document.documentElement.classList.remove('dark');
					localStorage.setItem('color-theme', 'light');
				}

				// if NOT set via local storage previously
			} else {
				if (document.documentElement.classList.contains('dark')) {
					document.documentElement.classList.remove('dark');
					localStorage.setItem('color-theme', 'light');
				} else {
					document.documentElement.classList.add('dark');
					localStorage.setItem('color-theme', 'dark');
				}
			}

		});
	</script>
	
	{% block js %}{% endblock js %}

	<script>
        let menuBtn = document.querySelector('.menu');
        let menuList = document.querySelector('.menuList');
        menuBtn.addEventListener('click', () => toggleMenu());
        const toggleMenu = () => {
            if (menuList.classList.contains('hidden')) {
                menuList.classList.add('block');
                menuList.classList.remove('hidden');
            }
            else{
                menuList.classList.add('hidden');
                menuList.classList.remove('block');
            }
        }
    </script>
</body>

</html>

templates/layouts/blog.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Color y alegria</title>
    
    <link rel="icon" href="{% static 'src/img/logo-icon.ico' %}">

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

    <style>
        ::-webkit-scrollbar {
            width: 5px;
        }
        ::-webkit-scrollbar-track {
            background: #2D3748;
        }
        ::-webkit-scrollbar-thumb {
            background: #CBD5E0;
        }
        ::-webkit-scrollbar-thumb:hover {
            background: #2D3748;
        }
    </style>
    {% block css %}{% endblock css %}

    <script>
		// On page load or when changing themes, best to add inline in `head` to avoid FOUC
		if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
			document.documentElement.classList.add('dark');
		} else {
			document.documentElement.classList.remove('dark')
		}
	</script>
    
</head>

<body class="bg-gray-100 dark:bg-gray-900">

    <div class="bg-gray-100 font-roboto">
        <nav class="px-6 py-4 bg-white shadow dark:bg-gray-800 dark:border-black dark:border-b-2">
            <div class="container flex flex-col mx-auto md:flex-row md:items-center md:justify-between">
                <div class="flex items-center justify-between">
                    <div>
                        <a href="{% url 'index' %}" class="text-xl font-bold text-gray-800 md:text-2xl dark:text-white">Color y <span class="text-blue-500">alegria</span></a>
                    </div>
                    <div class="flex items-center justify-end">
                        <div class="mx-6">
                            <button id="theme-toggle" type="button" class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
                                <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path>
                                </svg>
                                <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path>
                                </svg>
                            </button>
                        </div>
                        <button type="button" class="block text-gray-800 menu hover:text-gray-600 focus:text-gray-600 focus:outline-none md:hidden dark:text-gray-400">
                            <svg viewBox="0 0 24 24" class="w-6 h-6 fill-current">
                                <path d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"></path>
                            </svg>
                        </button>
                    </div>
                </div>
                <div class="flex flex-col hidden menuList md:flex-row md:-mx-4 md:block max-md:mt-5">
                    <a href="{% url 'index' %}" class="{% if request.get_full_path == '/' %} font-bold dark:text-white {% endif %} my-1 text-gray-800 dark:text-gray-400 dark:hover:text-white hover:text-blue-500 md:mx-4 md:my-0">Inicio</a>
                    <a href="{% url 'blog:index' %}" class="{% if 'blog' in request.path %} font-bold dark:text-white {% endif %} my-1 text-gray-800 dark:text-gray-400 dark:hover:text-white hover:text-blue-500 md:mx-4 md:my-0">Blog</a>
                    <a href="{% url 'nosotros' %}" class="{% if 'nosotros' in request.path %} font-bold dark:text-white {% endif %} my-1 text-gray-800 dark:text-gray-400 dark:hover:text-white hover:text-blue-500 md:mx-4 md:my-0">Nosotros</a>

                    {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' %}" class="{% if 'users' in request.path %} font-bold dark:text-white {% endif %} my-1 text-gray-800 dark:text-gray-400 dark:hover:text-white hover:text-blue-500 md:mx-4 md:my-0">Perfil</a> 
                    {% if user.is_admin %}
                    <a href="{% url 'posts:index' %}" class="my-1 text-gray-800 dark:text-gray-400 dark:hover:text-white hover:text-blue-500 md:mx-4 md:my-0">Admin</a> 
                    {% endif %}
                    <a href="{% url 'logout' %}" class="my-1 text-gray-800 dark:text-gray-400 dark:hover:text-white hover:text-blue-500 md:mx-4 md:my-0">Cerrar sesion</a> 
                    {% else %}
                    <a href="{% url 'login' %}" class="my-1 text-gray-800 dark:text-gray-400 dark:hover:text-white hover:text-blue-500 md:mx-4 md:my-0">Iniciar sesion</a>
                    <a href="{% url 'users:register' %}" class="my-1 text-gray-800 dark:text-gray-400 dark:hover:text-white hover:text-blue-500 md:mx-4 md:my-0">Registrarme</a>
                    {% endif %}
                    
                </div>
            </div>
        </nav>
        <div class="dark:bg-gray-900">
            
            {% block content %}{% endblock content %}

        </div>
        
        {% block footer %}
        <footer class="px-6 py-3 text-gray-100 bg-gray-800">
            <div class="container flex flex-col items-center justify-between mx-auto md:flex-row">
                <a href="#" class="text-2xl font-bold">Color y <span class="text-blue-500">alegria</span></a>
                <p class="mt-2 md:mt-0">Color y alegria 2022.</p>
                <div class="flex mt-4 mb-2 -mx-2 md:mt-0 md:mb-0">
                    <a href="https://www.facebook.com/profile.php?id=100070747194751&mibextid=ZbWKwL" target="_blank" class="mx-2 text-gray-100 hover:text-gray-400">
                        <svg viewBox="0 0 512 512" class="w-4 h-4 fill-current">
                            <path d="M455.27,32H56.73A24.74,24.74,0,0,0,32,56.73V455.27A24.74,24.74,0,0,0,56.73,480H256V304H202.45V240H256V189c0-57.86,40.13-89.36,91.82-89.36,24.73,0,51.33,1.86,57.51,2.68v60.43H364.15c-28.12,0-33.48,13.3-33.48,32.9V240h67l-8.75,64H330.67V480h124.6A24.74,24.74,0,0,0,480,455.27V56.73A24.74,24.74,0,0,0,455.27,32Z"></path>
                        </svg>
                    </a>
                    <a href="#" class="mx-2 text-gray-100 hover:text-gray-400">
                        <svg viewBox="0 0 512 512" class="w-4 h-4 fill-current">
                            <path d="M496,109.5a201.8,201.8,0,0,1-56.55,15.3,97.51,97.51,0,0,0,43.33-53.6,197.74,197.74,0,0,1-62.56,23.5A99.14,99.14,0,0,0,348.31,64c-54.42,0-98.46,43.4-98.46,96.9a93.21,93.21,0,0,0,2.54,22.1,280.7,280.7,0,0,1-203-101.3A95.69,95.69,0,0,0,36,130.4C36,164,53.53,193.7,80,211.1A97.5,97.5,0,0,1,35.22,199v1.2c0,47,34,86.1,79,95a100.76,100.76,0,0,1-25.94,3.4,94.38,94.38,0,0,1-18.51-1.8c12.51,38.5,48.92,66.5,92.05,67.3A199.59,199.59,0,0,1,39.5,405.6,203,203,0,0,1,16,404.2,278.68,278.68,0,0,0,166.74,448c181.36,0,280.44-147.7,280.44-275.8,0-4.2-.11-8.4-.31-12.5A198.48,198.48,0,0,0,496,109.5Z"></path>
                        </svg>
                    </a>
                </div>
            </div>
        </footer>
        {% endblock footer %}

    </div>

    <script>
		var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
		var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

		// Change the icons inside the button based on previous settings
		if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
			themeToggleLightIcon.classList.remove('hidden');
		} else {
			themeToggleDarkIcon.classList.remove('hidden');
		}

		var themeToggleBtn = document.getElementById('theme-toggle');

		themeToggleBtn.addEventListener('click', function () {

			// toggle icons inside button
			themeToggleDarkIcon.classList.toggle('hidden');
			themeToggleLightIcon.classList.toggle('hidden');

			// if set via local storage previously
			if (localStorage.getItem('color-theme')) {
				if (localStorage.getItem('color-theme') === 'light') {
					document.documentElement.classList.add('dark');
					localStorage.setItem('color-theme', 'dark');
				} else {
					document.documentElement.classList.remove('dark');
					localStorage.setItem('color-theme', 'light');
				}

				// if NOT set via local storage previously
			} else {
				if (document.documentElement.classList.contains('dark')) {
					document.documentElement.classList.remove('dark');
					localStorage.setItem('color-theme', 'light');
				} else {
					document.documentElement.classList.add('dark');
					localStorage.setItem('color-theme', 'dark');
				}
			}

		});
	</script>

    {% block js %}{% endblock js %}
    
    <script>
        let menuBtn = document.querySelector('.menu');
        let menuList = document.querySelector('.menuList');
        menuBtn.addEventListener('click', () => toggleMenu());
        const toggleMenu = () => {
            if (menuList.classList.contains('hidden')) {
                menuList.classList.add('block');
                menuList.classList.remove('hidden');
            }
            else{
                menuList.classList.add('hidden');
                menuList.classList.remove('block');
            }
        }
    </script>
</body>

</html>