apps/categories/urls.py
from django.urls import path
from . import views

app_name='categories'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/', views.Create.as_view(), name='create'),
    path('edit/<int:pk>', views.Edit.as_view(), name='edit'),
    path('delete/<int:pk>', views.Delete.as_view(), name='delete'),
]

color_y_alegria/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('nosotros/', views.nosotros, name='nosotros'),

    #includes
    path('categories/', include('apps.categories.urls')),
    path('users/', include('apps.users.urls')),
    path('posts/', include('apps.posts.urls')),
    path('blog/', include('apps.blog.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/categories/models.py
from django.db import models

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = True
        db_table = 'categories'

apps/categories/forms.py
from django import forms
from .models import Categories

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = ['name', 'description']

apps/categories/views.py
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from .forms import CategoryForm

from utils.mixins import IsAdminMixin

from apps.categories.models import Categories

# Create your views here.
class Index(IsAdminMixin, ListView):
    template_name = 'categories/index.html'
    model = Categories
    context_object_name = 'categories'
    paginate_by = 10

    def get_queryset(self):
        productos = Categories.objects.all()
        return productos.order_by('-id')

class Create(IsAdminMixin, CreateView):
    model = Categories 
    template_name = 'categories/create.html'
    form_class = CategoryForm

    def get_success_url(self):
        return reverse('categories:index')

class Edit(IsAdminMixin, UpdateView):
    model = Categories
    template_name = 'categories/edit.html'
    form_class = CategoryForm     

    def get_success_url(self):
        return reverse('categories:index')

class Delete(IsAdminMixin, DeleteView):
    model = Categories

    def get_success_url(self):
        return reverse('categories:index')

templates/categories/create.html
{% extends 'layouts/app.html' %}

{% block content %}

<div class="mx-2 my-4 bg-white dark:bg-gray-800">
    <div class="flex items-center justify-between px-4 py-3 border-b dark:border-gray-700">
        <h2 class="text-lg font-medium text-gray-700 dark:text-gray-400">Nueva Categoria</h2>
    </div>
    <div class="p-3 text-gray-600">
        <form method="POST">
            {% csrf_token %}
            
            <div class="flex p-2">
                <label class="inline w-1/4 py-2 pr-4 text-right dark:text-gray-400" for="{{ form.name.id_for_label }}">Nombre</label>
                <div class="w-full">
            
                    <input type="text" name="name" value="{{ form.name.value|default_if_none:"" }}" maxlength="30" required="" id="{{ form.name.id_for_label }}" placeholder="Nombre" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                
                    <span class="text-sm text-red-600">{{ form.name.errors }}</span>
                </div>
            </div>

            <div class="flex p-2">
                <label class="inline w-1/4 py-2 pr-4 text-right dark:text-gray-400" for="{{ form.description.id_for_label }}">Descripcion</label>
                <div class="w-full">

                    <textarea id="{{ form.description.id_for_label }}" name="description"
                        class="min-h-[100px] focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent"
                         placeholder="Ingrese una descripcion"
                        spellcheck="false">{{ form.description.value|default_if_none:"" }}</textarea>

                    <span class="text-sm text-red-600">{{ form.description.errors }}</span>
                </div>
            </div>

            <div class="flex p-2 mt-4">
                <label class="inline w-1/4 py-2 pr-4 text-right"></label>
                <div class="w-full">
                    <button class="inline-flex items-center px-4 py-2 text-sm text-white transition duration-150 ease-in-out bg-green-500 border border-transparent rounded hover:bg-green-400 focus:outline-none focus:border-green-500 focus:shadow-outline-green active:bg-green-500 dark:bg-green-800 dark:hover:bg-green-700">
                        Crear
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/categories/edit.html
{% extends 'layouts/app.html' %}

{% block content %}

<div class="mx-2 my-4 bg-white dark:bg-gray-800">
    <div class="flex items-center justify-between px-4 py-3 border-b dark:border-gray-700">
        <h2 class="text-lg font-medium text-gray-700 dark:text-gray-400">Editar Categoria</h2>
    </div>
    <div class="p-3 text-gray-600">
        <form method="POST">
            {% csrf_token %}
            
            <div class="flex p-2">
                <label class="inline w-1/4 py-2 pr-4 text-right dark:text-gray-400" for="{{ form.name.id_for_label }}">Nombre</label>
                <div class="w-full">
            
                    <input type="text" name="name" value="{{ form.name.value }}" maxlength="255" required="" id="{{ form.name.id_for_label }}" placeholder="Nombre" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                
                    <span class="text-sm text-red-600">{{ form.name.errors }}</span>
                </div>
            </div>

            <div class="flex p-2">
                <label class="inline w-1/4 py-2 pr-4 text-right dark:text-gray-400" for="{{ form.description.id_for_label }}">Descripcion</label>
                <div class="w-full">

                    <textarea id="{{ form.description.id_for_label }}" name="description"
                        class="min-h-[100px] focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent"
                         placeholder="Ingrese una descripcion"
                        spellcheck="false">{{ form.description.value }}</textarea>

                    <span class="text-sm text-red-600">{{ form.description.errors }}</span>
                </div>
            </div>

            <div class="flex p-2 mt-4">
                <label class="inline w-1/4 py-2 pr-4 text-right"></label>
                <div class="w-full">
                    <button class="inline-flex items-center px-4 py-2 text-sm text-white transition duration-150 ease-in-out bg-green-500 border border-transparent rounded hover:bg-green-400 focus:outline-none focus:border-green-500 focus:shadow-outline-green active:bg-green-500 dark:bg-green-800 dark:hover:bg-green-700">
                        Guardar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<style>input{background-clip: text;}</style>
{% endblock content %}

templates/categories/index.html
{% extends 'layouts/app.html' %}

{% block content %}

<div class="flex items-center justify-between px-4 py-2 mb-2 text-gray-600 border-b-2 rounded-t-lg dark:bg-gray-700 dark:text-gray-400 dark:border-gray-700">
    <h3 class="font-medium tracking-wider">Categorias</h3>
    <a href="{% url 'categories:create' %}"
        class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Nueva categoria</a>
</div>

<div class="px-2">
    <div id="dataContainer">
        <div class="relative overflow-auto">
            <table class="min-w-full mb-4 divide-y divide-gray-200 table-fixed dark:divide-gray-900 dark:bg-gray-900">
                <thead>
                    <tr>
                        <th scope="col" class="w-[50px] p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
                        <th scope="col" class="p-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">Nombre</th>
                        <th scope="col" class="max-w-[250px] p-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">Descripcion</th>
                        <th scope="col" class="w-[145px] p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Creacion</th>
                        <th scope="col" class="w-[145px] p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actualizacion</th>
                        <th scope="col" class="w-[100px] p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Opciones</th>
                    </tr>
                </thead>
                <tbody class="text-sm text-gray-500 divide-y divide-gray-200 dark:bg-gray-800 dark:divide-gray-900">
                    
                    {% for category in categories %}
                    <tr class="odd:bg-gray-100 even:bg-white dark:odd:bg-transparent dark:even:bg-gray-700">
                        <td class="p-3 dark:text-gray-400 whitespace-nowrap">{{ category.id }}</td>
                        <td class="p-3 text-sm text-gray-500 whitespace-pre-line dark:text-gray-400">{{ category.name }}</td>
                        <td class="p-3 text-sm text-gray-500 whitespace-pre-line dark:text-gray-400">{{ category.description }}</td>
                        <td class="p-3 text-sm text-gray-500 whitespace-pre-line dark:text-gray-400">{{category.created_at}}</td>
                        <td class="p-3 text-sm text-gray-500 whitespace-pre-line dark:text-gray-400">{{category.updated_at}}</td>
                        <td class="p-3 text-sm text-blue-600 dark:text-blue-400 whitespace-nowrap">
                            <a href="{% url 'categories:edit' category.id %}">Editar</a> |
                            <button class="delete" data-id="{{ category.id }}" data-name="{{ category.name }}">Eliminar</button>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="6" class="py-4 text-center whitespace-nowrap">No se encontraron categorias.</td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
        <div class="fixed top-0 left-0 right-0 z-50 flex items-center justify-center p-4 overflow-x-hidden overflow-y-auto overlay hidden_ md:inset-0 h-modal md:h-full">
            <div class="relative w-full h-full max-w-md modal_ hidden_ md:h-auto">
                <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                    <button type="button" class="btn-close absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white">
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                    <div class="p-6 text-center">
                        <svg aria-hidden="true" class="mx-auto mb-4 text-gray-400 w-14 h-14 dark:text-gray-200" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                        <h3 class="mb-4 text-lg font-normal text-gray-500 dark:text-gray-400">Seguro que desea eliminar el registro <b id="targetContent"></b>?</h3>
                        <div class="mb-2">
                            <span id="targetId" class="text-gray-500 dark:text-gray-400"></span>
                        </div>
                        <form method="POST" action="" name="formDelete">
                            {% csrf_token %}
                            <input type="submit" value="Confirmar" class="cursor-pointer text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block css %}
<style>
    .modal_ {
        position: absolute;
        z-index: 2;
        top: 15%;
        
    }

    .overlay {
        position: fixed;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5);
        backdrop-filter: blur(3px);
        z-index: 1;
    }

    .hidden_ {
        display: none;
    }
</style>
{% endblock css %}

{% block js %}
<script>
    const modal = document.querySelector('.modal_');
    const overlay = document.querySelector('.overlay');
    const openModalBtn = document.querySelector('#dataContainer');
    const closeModalBtn = document.querySelector('.btn-close');
    const targetId = document.querySelector('#targetId');
    const targetContent = document.querySelector('#targetContent');

    // close modal function
    const closeModal = function () {
        targetId.innerHTML = '';
        targetContent.innerHTML = '';

        modal.classList.add('hidden_');
        overlay.classList.add('hidden_');
    };

    // close the modal when the close button and overlay is clicked
    closeModalBtn.addEventListener('click', closeModal);
    overlay.addEventListener('click', closeModal);

    // close modal when the Esc key is pressed
    document.addEventListener('keydown', function (e) {
        if (e.key === 'Escape' && !modal.classList.contains('hidden_')) {
            closeModal();
        }
    });

    // open modal function
    const openModal = (e) => {
        let idData = e.target.getAttribute('data-id');
        let nameData = e.target.getAttribute('data-name');

        console.log(idData);

        targetId.insertAdjacentHTML('beforeend', `(ID: ${idData})`);
        targetContent.insertAdjacentHTML('beforeend', nameData);
        document.formDelete.action = 'delete/' + idData;

        modal.classList.remove('hidden_');
        overlay.classList.remove('hidden_');
    };

    // open modal event
    openModalBtn.addEventListener('click', (e) => {
        if (e.target && e.target.tagName === 'BUTTON') {
            openModal(e);
        }
    });
</script>
{% endblock js %}