apps/blog/urls.py
from django.urls import path

from . import views

app_name='blog'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('<slug>', views.Show, name='show'),
    path('category/<int:category_id>', views.category, name='category')
]

apps/users/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name="users"

urlpatterns = [
    path('register/', views.Registro.as_view(), name="register"),
    path('profile/', views.Profile, name='profile'),
]

color_y_alegria/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('nosotros/', views.nosotros, name='nosotros'),

    #includes
    path('categories/', include('apps.categories.urls')),
    path('users/', include('apps.users.urls')),
    path('posts/', include('apps.posts.urls')),
    path('blog/', include('apps.blog.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models

# Create your models here.

apps/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage
from apps.comments.forms import CommentForm
from apps.comments.models import Comments
from apps.media.models import Media
from apps.posts.models import Posts
from apps.categories.models import Categories

# Create your views here.
class Index(ListView):
    template_name = 'blog/index.html'
    model = Posts
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        posts = Posts.objects.all()
        return posts

    def get_context_data(self, *args, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['page_obj'] = context.pop('page_obj', None)
        context['categories'] = Categories.objects.all()
        return context

def Show(request, slug):
    post = get_object_or_404(Posts, slug = slug)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post = post
            form.user_id = request.user.id
            form.save()

            return redirect('blog:show', slug = slug)
    else:
        form = CommentForm()

    categories = Categories.objects.filter(id = post.category_id)
    comments = Comments.objects.filter(post_id = post.id)
    photos = Media.objects.filter(post_id = post.id)
    context = {'post': post, 'categories': categories, 'comments': comments, 'photos': photos,'form': form}

    return render(request, 'blog/show.html', context)


def category(request, category_id):
    try:
        category = get_object_or_404(Categories, id=category_id)
        posts = Posts.objects.filter(category=category_id)
        
        paginator = Paginator(posts, 5)
        page = request.GET.get('page')
        posts = paginator.get_page(page)

        return render(request, 'category/category.html',{'category':category, 'posts':posts, 'page_obj': posts, 'is_paginated': True, 'categories': Categories.objects.all})
    except:
        return render(request, 'blog/show.html')

templates/blog/index.html
{% extends 'layouts/blog.html' %}

{% block content %}
<div class="px-6 py-8">
    <div class="container flex justify-between mx-auto">
        <div class="w-full lg:w-8/12">
            {% for post in posts %}
            <div class="mt-6">
                <div class="px-10 py-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
                    <div class="flex items-center justify-between"><span class="font-light text-gray-600 dark:text-gray-400">{{ post.updated_at }}</span>
                        {% if post.category.id is null %}
                        <a href="{% url 'blog:index' %}" class="px-2 py-1 font-bold text-gray-100 transition duration-300 bg-blue-500 rounded hover:bg-gray-500">Sin categoria</a>
                        {% else %}
                        <a href="{% url 'blog:category' post.category.id %}" class="px-2 py-1 font-bold text-gray-100 transition duration-300 bg-blue-500 rounded hover:bg-gray-500">{{ post.category.name }}</a>
                        {% endif %}
                    </div>
                    <div class="mt-2">
                        <a href="{% url 'blog:show' post.slug %}" class="text-2xl font-bold text-gray-700 dark:text-gray-200 hover:underline">{{ post.title }}</a>
                        <div class="mt-2 text-gray-600 dark:text-gray-400">{{ post.body|safe|truncatewords:100 }}</div>
                    </div>
                    <div class="flex items-center justify-between mt-4">
                        <a href="{% url 'blog:show' post.slug %}"class="text-blue-500 hover:underline">Leer mas...</a>
                        <div>
                            <a href="#" class="flex items-center">
                                {% if post.user.photo %}
                                <img src="{{post.user.photo.url}}" alt="avatar" class="hidden object-cover w-10 h-10 mx-4 rounded-full sm:block dark:bg-gray-600 ring-2 ring-gray-400 dark:ring-gray-500">
                                {% else %}
                                <div class="relative w-10 h-10 mx-4 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600 ring-2 ring-gray-300 dark:ring-gray-500">
                                    <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                                </div>
                                {% endif %}
                                <h1 class="font-bold text-gray-700 dark:text-gray-400 hover:underline">{{ post.user.username }}</h1>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="mt-6">
                <div class="px-10 py-6 bg-white rounded-lg shadow-md">No se encontraron publicaciones.</div>
            </div>
            {% endfor %}
            
            {% include 'includes/paginate.html' %}

        </div>
        <div class="hidden w-4/12 -mx-8 lg:block">
            <div class="px-8 mt-2">
                <h1 class="mb-4 text-xl font-bold text-gray-700 dark:text-gray-500">Categorias</h1>
                <div class="flex flex-col max-w-sm px-4 py-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
                    <ul>
                        {% for category in categories %}
                        <li class="mt-2">
                            <a href="{% url 'blog:category' category.id %}" class="mx-1 font-bold text-gray-700 dark:text-gray-400 hover:text-gray-600 hover:underline">- {{ category.name }}</a>
                        </li>
                        {% empty %}
                        <li class="mt-2">
                            <a href="#" class="mx-1 font-bold text-gray-700 dark:text-gray-400">- No se encontraron categorias</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/show.html
{% extends 'layouts/blog.html' %}

{% block content %}

<div class="pb-8">
    <section class="">

    {% if photos %}
        {% for photo in photos %}
            {% if photo.is_first == 1 %}
            <div class="mb-12 bg-no-repeat bg-cover" style="background-image: url('{{photo.photo.url}}');">       
            {% endif %}
        {% endfor %}
    {% else %}
            <div class="mb-12 bg-no-repeat bg-cover">
    {% endif %}

            <div class="max-md:px-4" style="background-color: rgb(0 0 0 / 65%);">
                <div class="max-w-2xl pt-32 pb-20 mx-auto">
                    <div class="mb-6 text-center">
                        <span class="text-base md:text-lg">
                            {% if post.category.id is null %}
                            <a href="{% url 'blog:index' %}" class="text-gray-200 hover:underline">
                                <span class="inline-block px-3 py-1 mr-3 text-xs font-semibold text-blue-600 bg-blue-100 rounded-xl">Sin categoria</span>
                            </a>
                            {% else %}
                            <a href="{% url 'blog:category' post.category.id %}" class="text-gray-200 hover:underline">
                                <span class="inline-block px-3 py-1 mr-3 text-xs font-semibold text-blue-600 bg-blue-100 rounded-xl">{{ post.category.name }}</span>
                            </a>
                            {% endif %}
                            <span class="text-sm text-gray-400">{{ post.updated_at }}</span>
                        </span>
                        <h2 class="mt-4 text-4xl font-bold text-gray-100 md:text-5xl font-heading">{{ post.title }}</h2>
                    </div>
                    <div class="flex justify-center mb-8">
                        {% if post.user.photo %}
                        <img class="object-cover w-12 h-12 rounded-full ring-2 ring-gray-400 dark:ring-gray-500" src="{{post.user.photo.url}}" alt="">
                        {% else %}
                        <div class="relative w-12 h-12 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600 ring-2 ring-gray-400 dark:ring-gray-500">
                            <svg class="absolute text-gray-400 w-14 h-14 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                        </div>
                        {% endif %}
                        <div class="pl-4">
                            <p class="mb-1 text-gray-400">{{ post.user.first_name }} {{ post.user.last_name }}</p>
                            <p class="text-xs font-semibold text-gray-400">{{ post.user }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mx-auto max-md:px-2">
            
            <div id="post" class="max-w-2xl mx-auto max-sm:px-4">
                <div class="mb-6 text-lg leading-loose text-gray-800 dark:text-gray-400">{{ post.body|safe }}</div>
            </div>

            <div class="overflow-hidden text-gray-700">
                <div class="container px-5 py-2 mx-auto lg:pt-12 lg:px-32">
                    <div class="flex flex-wrap -m-1 md:-m-2">
                        {% for photo in photos %}
                            {% if not photo.is_first == 1 %}
                            <div class="flex flex-wrap w-1/3 mx-auto max-md:w-1/2 max-sm:w-full">
                                <div class="w-full h-64 p-1 transition-all rounded-lg md:p-2 hover:bg-opacity-80 hover:bg-blue-400">
                                    <a href="{{photo.photo.url}}" target="_blank" class="transition-all hover:opacity-70 ">
                                        <img src="{{photo.photo.url}}" alt="{{photo.id}}" class="block object-cover object-center w-full h-full rounded-lg">
                                    </a>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>

            <!-- <div class="pt-40 pb-40 mb-12 bg-center bg-no-repeat bg-cover rounded-xl"
                style="background-image: url(&quot;assets/imgs/placeholders/img-8.png&quot;);">
                <div class="max-w-2xl mx-auto">
                    <div class="mb-6 text-center"></div>
                </div>
            </div> -->
            <div class="max-w-2xl mx-auto mt-10 mb-6">
                <div class="w-full">
                    <div class="px-6 py-10 bg-white border border-gray-100 rounded shadow dark:bg-gray-800 dark:border-none"
                        data-wow-delay=".1s" style="visibility: visible; animation-delay: 0.1s;">
                        <div class="flex items-center">
                            {% if post.user.photo %}
                            <img class="object-cover w-16 h-16 rounded-full dark:bg-gray-600 ring-2 ring-gray-400 dark:ring-gray-500" src="{{post.user.photo.url}}" alt="">
                            {% else %}
                            <div class="relative overflow-hidden bg-gray-100 rounded-full w-14 h-14 dark:bg-gray-600 ring-2 ring-gray-300 dark:ring-gray-500">
                                <svg class="absolute w-16 h-16 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                            </div>
                            {% endif %}
                            <div class="pl-4">
                                <strong class="mt-6 mb-1 text-gray-700 dark:text-gray-400 text-md">{{ post.user.first_name }} {{ post.user.last_name }}</strong>
                                <p class="mt-3 text-xs text-gray-700 dark:text-gray-400">{{ post.user }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<div class="pt-12 bg-white max-md:px-4 dark:bg-gray-800">
    <div class="max-w-2xl mx-auto">
        <div class="max-w-screen-sm mx-auto antialiased">
            <h3 class="mb-6 text-3xl font-semibold text-gray-700 dark:text-gray-200">Comentarios</h3>
            <div class="space-y-4">
                {% for comment in comments %}
                <div class="flex">
                    <div class="flex-shrink-0 mr-3">
                        {% if comment.user.photo %}
                        <img class="object-cover w-8 h-8 mt-2 rounded-full sm:w-10 sm:h-10 dark:bg-gray-600 ring-2 ring-gray-400 dark:ring-gray-500" src="{{comment.user.photo.url}}" alt="">
                        {% else %}
                        <div class="relative w-8 h-8 overflow-hidden bg-gray-100 rounded-full sm:w-10 sm:h-10 dark:bg-gray-600 ring-2 ring-gray-300 dark:ring-gray-500">
                            <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                        </div>
                        {% endif %}
                    </div>
                    <div class="flex-1 px-4 py-2 leading-relaxed border border-gray-200 rounded-lg sm:px-6 sm:py-4 dark:border-gray-700">
                        <strong class="dark:text-gray-200">{{ comment.user }}</strong>
                        <span class="ml-2 text-xs text-gray-400">{{ comment.created_at }}</span>
                        <div class="text-sm break-all dark:text-gray-400">{{ comment.body|linebreaksbr }}</div>
                    </div>
                </div>
                {% empty%}
                <div class="mt-4 text-gray-500 dark:text-gray-400">No hay comentarios, se el primero en comentar</div>
                {% endfor %}
            </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class="mt-12 mb-4">
            <form action="" method="POST" class="w-full bg-white rounded-lg dark:bg-gray-800">
                {% csrf_token %}
                <div class="flex flex-wrap mb-6">
                    <h2 class="pt-3 pb-2 text-lg font-bold text-gray-700 dark:text-gray-400">Danos tu opinion</h2>
                    <div class="w-full mt-2 mb-2 md:w-full">
                        <textarea name="body" placeholder="Escriba un comentario" required="" class="w-full h-32 px-3 py-4 text-sm leading-normal bg-gray-100 border border-gray-300 rounded resize-none focus:ring-2 focus:bg-white focus:border-blue-500 focus:outline-none focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent"></textarea>
                    </div>
                    <button class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        Comentar
                    </button>
                </div>
            </form>
        </div>
        {% else %}
        <div class="mt-12 mb-4">
            <h2 class="pt-3 pb-2 text-lg font-bold text-center text-gray-500 dark:text-gray-400">
                <a href="{% url 'login' %}" class="text-gray-700 underline hover:text-blue-500 dark:text-gray-200 dark:hover:text-blue-500">Inicie sesión</a> o <a href="{% url 'users:register' %}" class="text-gray-700 underline hover:text-blue-500 dark:text-gray-200 dark:hover:text-blue-500">Regístrese</a> para dejar su comentario
            </h2>
        </div>
        {% endif %}
        <div class="flex items-center justify-center pb-10">
            <a href="{% url 'blog:index' %}" class="px-4 py-2 mt-2 text-gray-600 border border-gray-300 rounded-lg dark:text-gray-200 dark:border-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none">
                Leer otras publicaciones
            </a>
        </div>
    </div>
</div>

{% endblock content %}

{% block css %}
<style>
    #post h1,
    #post h2,
    #post h3,
    #post h4,
    #post h5,
    #post h6{
        margin-bottom: 1.5rem;
        font-weight: bold;
    }
    #post h1{
        font-size: 2rem;
    }
    #post h2{
        font-size: 1.5rem;
    }
    #post h3{
        font-size: 1.4rem;
    }
    #post p{
        margin-bottom: 1.5rem;
    }
    #post table{
        border-collapse: collapse;
        margin: 1.5rem 0;
    }
    #post span{
        padding: .5rem .3rem;
    }
    #post td, #post th {
        border: 1px solid #000;
        padding: 0 .5rem;
    }
</style>
{% endblock css %}