apps/users/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name="users"

urlpatterns = [
    path('register/', views.Registro.as_view(), name="register"),
    path('profile/', views.Profile, name='profile'),
]

color_y_alegria/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('nosotros/', views.nosotros, name='nosotros'),

    #includes
    path('categories/', include('apps.categories.urls')),
    path('users/', include('apps.users.urls')),
    path('posts/', include('apps.posts.urls')),
    path('blog/', include('apps.blog.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Users(AbstractUser):
    photo = models.ImageField(upload_to='users', null=True, blank=True, default=None)
    is_admin = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'users'

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


from .models import Users

class UserForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    
    class Meta:
        model=Users
        fields=["first_name", "last_name", "email", "username", "password1", "password2"]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['photo']

apps/users/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.urls import reverse

from .forms import ProfileForm
from .forms import UserForm
from .models import Users

class Registro(CreateView):
    model = Users 
    template_name = "users/register.html"
    form_class = UserForm

    def get_success_url(self):
        return reverse('login')

def Profile(request):
    user = Users.objects.get(id=request.user.id)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            if not request.FILES.get('photo') or request.FILES.get('photo').name == None:
                form = form.save(commit=False)
                form.photo = None

            form.save()
            return redirect('users:profile')

    photo = user.photo
    return render(request, 'users/profile.html', {'photo': photo})

templates/users/login.html
{% extends 'layouts/blog.html' %}

{% block content %}

<div class="px-6 py-10">
    <div class="flex items-center justify-center min-h-full sm:px-6 lg:px-8">
        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h2 class="mb-6 text-2xl font-extrabold leading-none tracking-tight text-center text-gray-700 dark:text-white">Iniciar sesion</h2>
                <form method="post">
                    {% csrf_token %}
                    
                    {% include 'includes/errors_form.html' %}
                
                    <div class="w-full mb-4">
                        <label for="username" class="dark:text-gray-400">Usuario</label>
                        <input type="text" name="username" value="" maxlength="255" autofocus="" required="" id="username" placeholder="Nombre" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                    </div>
                    <div class="w-full mb-4">
                        <label for="password" class="dark:text-gray-400">Contraseña</label>
                        <input type="password" name="password" value="" maxlength="255" required="" id="password" placeholder="Contraseña" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                    </div>
                
                    <div class="mt-4">
                        <button class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="submit" name="btn_ingresar">
                            Ingresar
                        </button>
                    </div>
                
                    <div class="mt-4 dark:text-gray-400">
                        <a class="font-medium text-blue-600 dark:text-blue-500 hover:underline" href="{% url 'index' %}">Volver al inicio</a> | 
                        <a class="font-medium text-blue-600 dark:text-blue-500 hover:underline" href="{% url 'users:register' %}">Registrarme</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block footer %} {% endblock footer %}

templates/users/profile.html
{% extends 'layouts/blog.html' %}

{% block content %}

<div class="px-6 py-10">
    <div class="container flex justify-between mx-auto">
        <div class="items-center w-1/2 mx-auto max-sm:w-full">
            <div class="mt-6 mb-10">
                <div class="px-10 py-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
                    <div class="mt-2">
                        <div class="">
                            <div class="p-1 md:p-2">
                                {% if request.user.photo %}
                                <div class="relative items-center w-32 h-32 mx-auto rounded-full dark:bg-gray-600 ring-2 ring-gray-400 dark:ring-gray-500">
                                    <img src="{{request.user.photo.url}}" class="block object-cover object-center w-full h-full rounded-full -left-1">
                                </div>
                                {% else %}
                                <div class="relative items-center w-32 h-32 mx-auto overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600 ring-2 ring-gray-400 dark:ring-gray-500">
                                    <svg class="absolute text-gray-400 w-26 h-26 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                                </div>
                                <div class="my-4 text-center text-gray-600">No tienes foto de perfil</div>
                                {% endif %}
                            </div>
                        </div>
                        <p href="" class="text-3xl font-bold text-center text-gray-700 dark:text-gray-200">{{request.user.first_name}} {{request.user.last_name}}</p>
                        <p href="" class="text-2xl font-bold text-center text-gray-500 dark:text-gray-400">@{{request.user.username}}</p>
                    </div>
                    <div class="items-center mt-8">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mt-4">
                                <input type="file" id="photo" name="photo" accept="image/png, image/jpg, image/jpeg, image/gif, image/webp, image/bmp, image/tiff" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:text-gray-400">
                            </div>
                            <div class="flex p-2 mt-4">
                                <div class="w-full">
                                    <button class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                                        Guardar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block footer %} {% endblock footer %}

templates/users/register.html
{% extends 'layouts/blog.html' %}

{% block content %}

<div class="px-6 py-10">
    <div class="flex items-center justify-center min-h-full sm:px-6 lg:px-8">
        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-screen-sm xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h2 class="mb-6 text-2xl font-extrabold leading-none tracking-tight text-center text-gray-700 dark:text-white">Registro</h2>
                
                <form method="POST">
                    {% csrf_token %}

                    {% include 'includes/errors_form.html' %}
                    
                    <div class="grid gap-6 mb-4 md:grid-cols-2">
                        <div>
                            <div class="w-full">
                                <label for="id_first_name" class="dark:text-gray-400">Nombre:</label>
                                <input type="text" name="first_name" autofocus="" required="" id="id_first_name" placeholder="Nombre" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                    
                                <span class="text-sm text-red-600"></span>
                            </div>
                        </div>
                        <div>
                            <div class="w-full">
                                <label for="id_last_name" class="dark:text-gray-400">Apellido:</label>
                                <input type="text" name="last_name" required="" id="id_last_name" placeholder="Apellido" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                            </div>
                        </div>
                    </div>
                    <div class="w-full mb-8">
                        <label for="id_email" class="dark:text-gray-400">Email:</label>
                        <input type="email" name="email" maxlength="254" id="id_email" placeholder="Email" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                    </div>
                    
                    <div class="w-full mb-4">
                        <label for="id_username" class="dark:text-gray-400">Usuario:</label>
                        <input type="text" name="username" maxlength="150" required="" id="id_username" placeholder="Usuario" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                    </div>
                    
                    <div class="w-full mb-4">
                        <label for="id_password1" class="dark:text-gray-400">Contraseña:</label>
                        <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" placeholder="Contraseña" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                    </div>
                    
                    <div class="w-full mb-4">
                        <label for="id_password2" class="dark:text-gray-400">Repetir contraseña:</label>
                        <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" placeholder="Repetir contraseña" class="focus:border-blue-400 focus:ring-2 focus:ring-blue-200 focus:outline-none w-full text-base placeholder-gray-400 border border-gray-300 rounded py-1.5 px-3 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-600 dark:focus:border-blue-500 dark:autofill:bg-transparent">
                    </div>

                    <div class="w-full my-6">
                        <h3 class="mb-2 font-medium text-blue-700 dark:text-blue-400">Su contraseña</h3>
                        <ul class="p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800">
                            <li class="font-medium">* No puede estar formada exclusivamente por números.</li>
                            <li class="font-medium">* Debe contener por lo menos 8 caracteres.</li>
                            <li class="font-medium">* Longitud máxima de 150 caracteres.</li>
                            <li class="font-medium">* Solo puede estar formado por letras, números y los caracteres @/./+/-/_.</li>
                        </ul>
                    </div>

                    <div class="mt-4">
                        <button type="submit" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            Registrarme
                        </button>
                    </div>
                </form>     
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %} {% endblock footer %}